apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  labels:
    app: carloscb
    service: mongo
spec:
  serviceName: mongo-service
  replicas: 2
  selector:
    matchLabels:
      app: carloscb
      service: mongo
  template:
    metadata:
      labels:
        app: carloscb
        service: mongo
    spec:
      containers:
        - name: carloscb
          image: mongo:4.2.3
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-volume
      spec:
        storageClassName: manual
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: carloscb
    service: mongo
  clusterIP: None
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017