apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: cb
    service: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cb
      service: back
  template:
    metadata:
      labels:
        app: cb
        service: back
    spec:
      containers:
        - name: back
          image: carloscb8080/cb-back:1.5.7-prerelease0
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: back-config
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 500m
              memory: 400Mi

---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    app: cb
    service: back
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
