apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-deployment
  labels:
    app: cb
    service: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cb
      service: nats
  template:
    metadata:
      labels:
        app: cb
        service: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:alpine3.18
          ports:
            - containerPort: 4222
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 500m
              memory: 400Mi

---
apiVersion: v1
kind: Service
metadata:
  name: nats-service
spec:
  selector:
    app: cb
    service: nats
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4222
      targetPort: 4222
