apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: cb
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cb
      service: redis
  template:
    metadata:
      labels:
        app: cb
        service: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 500m
              memory: 400Mi
            requests:
              cpu: 500m
              memory: 400Mi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: cb
    service: redis
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
