apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: carloscb
    service: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carloscb
      service: back
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: carloscb
        service: back
    spec:
      containers:
        - name: back
          image: carloscb8080/carloscb-back:0.0.3-prerelease-test
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: back-config
          resources:
            limits:
              cpu: 150m
              memory: 150Mi
            requests:
              cpu: 100m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    app: carloscb
    service: back
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
    - name: grpc
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
