apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: carloscb
    service: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carloscb
      service: front
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: carloscb
        service: front
    spec:
      containers:
        - name: carloscb
          image: carloscb8080/carloscb-front:0.0.0-prerelease-test
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: front-config
          resources:
            limits:
              cpu: 200m 
              memory: 150Mi
            requests:
              cpu: 200m 
              memory: 150Mi

---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: carloscb
    service: front
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
