apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: carloscb
    service: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carloscb
      service: redis
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: carloscb
        service: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 82m
              memory: 80Mi

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: carloscb
    service: redis
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
