
apiVersion: storage.k8s.io/v1 
kind: StorageClass
metadata:
  name: manual
provisioner: k8s.io/minikube-hostpath
parameters:
  type: directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: front-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

