apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: front-pvc
spec:
  storageClassName: default-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: front-pv
spec:
  storageClassName: default-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
    